#!/bin/sh

REPO="$HOME/dotfiles"

# Bash Stuff
ln -sf $REPO/bash/profile       $HOME/.profile
ln -sf $REPO/bash/bashrc        $HOME/.bashrc
ln -sf $REPO/bash/bash_aliases  $HOME/.bash_aliases
ln -sf $REPO/bash/bash_logout   $HOME/.bash_logout

# Vim
ln -sf $REPO/vim                $HOME/.vim
ln -sf $REPO/vim/vimrc          $HOME/.vimrc

# Conky
ln -sf $REPO/conky/simpledate/conkyrc.whitetext         $HOME/.conkyrc.whitetext
ln -sf $REPO/conky/simpledate/conkyrc.blacktext         $HOME/.conkyrc.blacktext

