alias lst='ls -l -ctF | head -10'
alias top3='/usr/bin/top -b -n 1 | tail +7 | head -n 4'

alias perldoc='perldoc -t'
alias vess='vim -u /usr/share/vim/vim72/macros/less.vim'

alias fixfanstyle='sed -i -e 's/\<head\>/\<head\>\ \<link\ rel\=\"stylesheet\"\ type\=\"text\/css\"\ href\=\".style.css\"''
alias mp='mplayer -vo xv -fs -zoom -stop-xscreensaver -nobps -alang en -input file=/tmp/mplayer.fifo'
